---
require:
- rubocop/require_tools
- rubocop-performance
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
  - "**/*.rb"
  - "**/*file"
  - "**/*.gemspec"
  - "*/lib/assets/*Template"
  - "*/lib/assets/*TemplateAndroid"
  Exclude:
  - "**/lib/assets/custom_action_template.rb"
  - "./vendor/**/*"
  - "**/lib/assets/DefaultFastfileTemplate"
  - "**/lib/assets/MatchfileTemplate"
  - "**/spec/fixtures/broken_files/broken_file.rb"
  - "**/*.provisionprofile"

Layout/DotPosition:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/LineLength:
  Max: 370
Layout/SpaceAroundOperators:
  Exclude:
    - "**/spec/actions_specs/xcodebuild_spec.rb"

Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/ErbNewArguments:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - "**/spec/**/*"
Lint/SuppressedException:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/UselessAssignment:
  Exclude:
  - "**/spec/**/*"

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 320
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 17
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 20

Naming/FileName:
  Exclude:
    - "**/Dangerfile"
    - "**/Brewfile"
    - "**/Gemfile"
    - "**/Podfile"
    - "**/Rakefile"
    - "**/Fastfile"
    - "**/Deliverfile"
    - "**/Snapfile"
    - "**/Pluginfile"
    - "**/*.gemspec"
Naming/PredicateName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false
Performance/StringReplacement:
  Enabled: false

Require/MissingRequireStatement:
  Exclude:
  - "lib/fastlane/plugin/shake_bugs/**/*.rb"
  - "**/spec/**/*.rb"
  - "**/spec_helper.rb"
  - spaceship/lib/spaceship/babosa_fix.rb
  - fastlane_core/lib/fastlane_core/ui/disable_colors.rb
  - "**/Fastfile"
  - "**/*.gemspec"
  - rakelib/**/*
  - "**/*.rake"
  - "**/Rakefile"
  - fastlane/**/*
  - supply/**/*

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/CollectionMethods:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - require
    - require_relative
    - fastlane_require
    - gem
    - program
    - command
    - raise
    - attr_accessor
    - attr_reader
    - desc
    - lane
    - private_lane
    - platform
    - to
    - not_to
    - describe
    - it
    - be
    - context
    - before
    - after
Style/MissingRespondToMissing:
  Enabled: false
Style/MixinGrouping:
  Exclude:
  - "**/spec/**/*"
Style/MultilineBlockChain:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/WordArray:
  MinSize: 19
Style/ZeroLengthPredicate:
  Enabled: false
