module Message
  MISSING_CLIENT_ID = 'Client id must be specified'
  MISSING_CLIENT_SECRET = 'Client secret must be specified'

  MISSING_MAPPING_FILE = 'Could not find any mapping file generated by `gradle`'
  MISSING_APPLICATION_ID = 'Application id must be specified or apk must be provided for extraction'
  MISSING_VERSION_NAME = 'Version name must be specified or apk must be provided for extraction'
  MISSING_VERSION_CODE = 'Version code must be specified or apk must be provided for extraction'
  ANDROID_HOME_NOT_SET = 'ANDROID_HOME environment variable is not set'

  MISSING_DSYM_FILE = 'Could not find any dSYM file generated by `gym`'
  MISSING_BUNDLE_ID = 'Bundle id must be specified or ipa must be provided for extraction'
  MISSING_VERSION_NUMBER = 'Version number must be specified or ipa must be provided for extraction'
  MISSING_BUILD_NUMBER = 'Build number must be specified or ipa must be provided for extraction'

  AUTHENTICATION_SUCCEEDED = 'Authenticated successfully'
  AUTHENTICATION_FAILED = 'Please check your credentials'
  UPLOAD_SUCCEEDED = 'Mapping file uploaded successfully'

  def self.mapping_not_found(mapping_file)
    "Could not find mapping file at path #{mapping_file}"
  end

  def self.apk_not_found(apk)
    "Could not find apk at path #{apk}"
  end

  def self.dsym_not_found(dsym_file)
    "Could not find dSYM file at path #{dsym_file}"
  end

  def self.ipa_not_found(ipa)
    "Could not find ipa at path #{ipa}"
  end

  def self.upload_failed(error)
    "Error while uploading mapping file: #{error}"
  end
end
